name: flutter_ecom
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_native_splash: ^2.3.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  fpdart: ^1.0.0
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.7
  logger: ^2.0.1
  objectbox: 2.2.0
  objectbox_flutter_libs: 2.2.0
  path: ^1.8.3
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  go_router_builder: any
  import_sorter: ^4.6.0
  objectbox_generator: 2.2.0
  riverpod_generator: any
  riverpod_lint: ^2.0.1
  very_good_analysis: ^5.0.0+1

import_sorter:
  comments: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
